# Site settings
title: Juliette Bruce
email: juliette_bruce1@brown.edu
description: > # this means to ignore newlines until "baseurl:"
   Postdoctoral research associate in the Mathematics Department at Brown University. I combine homological
   and combinatorial techniques to study the geometry of solutions to systems polynomial equations.
   PhD from the University of Wisconsin, Madison.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.juliettebruce.xyz" # the base hostname & protocol for your site
production_url: "https://www.juliettebruce.xyz"
github_username: julietteBruce
permalink: /blog/:year/:month/:title.html

# Google Analytics
google_analytics: G-8EM71CZE11

twitter:
  username: julietteBruce

sass:
  style: compressed

collections:
  publications:
    output: false

jekyll-mentions:
  base_url: https://twitter.com

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-mentions
